name: Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - uses: actions/checkout@v4.1.1

    - name: Setup Python
      uses: mamba-org/setup-micromamba@v1.8.1
      with:
        environment-name: test
        create-args: >-
          python=3.11
          conda-project
          -c conda-forge
    - name: Install conda-project
      run: conda project install
    - name: Run conda-project
      run: |
        conda project run >> logs.txt
        sleep 5
        cat logs.txt
    - name: Check Panel app running
      run: |
        curl http://127.0.0.1:5000
